data = {
    'AAAI',
    'ACM Multimedia',
    'ACM SIGCOMM Conference',
    'ACM Transactions on Graphics (TOG)',
    'ACM Transactions on Multimedia Computing, Communications, and Applications',
    'Applied Soft Computing',
    'BMSB',
    'CCF Trans. Netw.',
    'CCF Transactions on Pervasive Computing and Interaction',
    'Collections',
    'Computer Graphics Forum',
    'Computer Networks',
    'Computer Vision and Image Understanding',
    'Computer Vision and Pattern Recognition',
    'Conference on Communications in China',
    'Conference on Multimedia Modeling',
    'DAS',
    'DCC',
    'Digit. Commun. Networks',
    'ECCV',
    'Emerging Intelligent Data and Web Technologies',
    'Entropy',
    'EuroSys',
    'Expert Systems with Applications',
    'ICASSP',
    'ICC',
    'ICCV',
    'ICCV Workshops',
    'ICMLC',
    'ICWS',
    'IEEE Access',
    'IEEE CAA J. Autom. Sinica',
    'IEEE Communications Letters',
    'IEEE Communications Magazine',
    'IEEE Communications Surveys and Tutorials',
    'IEEE GLOBECOM',
    'IEEE International Geoscience and Remote Sensing Symposium',
    'IEEE International Symposium on Circuits and Systems',
    'IEEE International Symposium on Personal, Indoor and Mobile Radio '
    'Communications',
    'IEEE Internet of Things Journal',
    'IEEE Internet of Things Magazine',
    'IEEE Journal of Selected Areas in Communications',
    'IEEE Journal of Selected Topics in Applied Earth Observations and Remote '
    'Sensing',
    'IEEE Journal of Selected Topics in Signal Processing',
    'IEEE Network',
    'IEEE Open J. Comput. Soc.',
    'IEEE Signal Processing Letters',
    'IEEE Transactions on Broadcasting',
    'IEEE Transactions on Circuits and Systems for Video Technology',
    'IEEE Transactions on Cognitive Communications and Networking',
    'IEEE Transactions on Communications',
    'IEEE Transactions on Computational Imaging',
    'IEEE Transactions on Cybernetics',
    'IEEE Transactions on Geoscience and Remote Sensing',
    'IEEE Transactions on Green Communications and Networking',
    'IEEE Transactions on Image Processing',
    'IEEE Transactions on Instrumentation and Measurement',
    'IEEE Transactions on Medical Imaging',
    'IEEE Transactions on Mobile Computing',
    'IEEE Transactions on Multimedia',
    'IEEE Transactions on Network Science and Engineering',
    'IEEE Transactions on Network and Service Management',
    'IEEE Transactions on Neural Networks [and Learning Systems]',
    'IEEE Transactions on Parallel and Distributed Systems',
    'IEEE Transactions on Pattern Analysis and Machine Intelligence (TPAMI)',
    'IEEE Transactions on Services Computing',
    'IEEE Transactions on Signal Processing',
    'IEEE Transactions on Smart Grid (TSG)',
    'IEEE Transactions on Vehicular Technology',
    'IEEE Transactions on Wireless Communications',
    'IEEE Wireless Communications',
    'IEEE Wireless Communications Letters',
    'IEEE/ACM Transactions on Audio, Speech and Language Processing',
    'IET Circuits, Devices & Systems',
    'IET Communications',
    'IET Image Processing',
    'IJCNN',
    'INFOCOM',
    'IWQoS',
    'International Conference on Algorithms and Architectures for Parallel '
    'Processing',
    'International Conference on Image Processing',
    'International Conference on Image and Graphics',
    'International Conference on Network Protocols',
    'International Conference on Parallel and Distributed Systems (ICPADS)',
    'International Conference on Pattern Recognition (ICPR)',
    'International Conference on Wireless Communications and Mobile Computing',
    'International Journal of Computer Vision',
    'International Journal of Digital Earth',
    'International Journal of Machine Learning and Cybernetics',
    'International Journal of Systems Assurance Engineering and Management',
    'Journal of Chemical Information and Modeling',
    'Journal of Computational and Applied Mathematics',
    'Journal of Network and Computer Applications',
    'Journal of Sensors',
    'Journal of Visual Communication and Image Representation',
    'Knowledge Based Systems',
    'MICCAI',
    'MIPR',
    'Mobile Adhoc and Sensor Systems - MASS',
    'Mobile Information Systems',
    'Mobile Networks and Applications (MONET)',
    'Mobile Sensor Networks',
    'Modeling Analysis and Simulation of Wireless and Mobile Systems',
    'Multimedia Computing and Systems',
    'Multimedia Tools and Applications',
    'NOSSDAV',
    'NeurIPS',
    'Neural Computing and Applications',
    'Neural Networks',
    'Neural Processing Letters',
    'Neurocomputing',
    'Pattern Recognition',
    'Peer-to-Peer Networking and Applications',
    'Picture Coding Symposium',
    'Remote Sensing',
    'Robotics Comput. Integr. Manuf.',
    'Scientific Programming',
    'Security and Communication Networks',
    'Sensors',
    'Signal, Image and Video Processing',
    'Vehicular Technology Conference',
    'Virtual Reality Conference',
    'Visual Communications and Image Processing',
    'WACV',
    'WOWMOM',
    'WWW',
    'Wireless Communications and Mobile Computing',
    'arXiv CoRR'
}
