data = {
    '3DV',
    '6GN',
    'AAAI',
    'ACCV (2)',
    'ACCV (4)',
    'ACCV Workshops',
    'ACL/IJCNLP (2)',
    'ACM Comput. Surv.',
    'ACM J. Data Inf. Qual.',
    'ACM Multimedia',
    'ACM Trans. Design Autom. Electr. Syst.',
    'ACM Trans. Graph.',
    'ACM Trans. Internet Techn.',
    'ACM Trans. Internet Things',
    'ACM Trans. Multim. Comput. Commun. Appl.',
    'ACM Trans. Sens. Networks',
    'ACSSC',
    'AIAI Workshops',
    'AISTATS',
    'APNOMS',
    'APSIPA ASC',
    'ASE',
    'ASICON',
    'Ad Hoc Networks',
    'Appl. Intell.',
    'Appl. Math. Comput.',
    'Appl. Soft Comput.',
    'Artif. Intell. Rev.',
    'BIBM',
    'BIC',
    'BIOSIGNALS',
    'BMC Bioinform.',
    'BMSB',
    'BMVC',
    'BSCI',
    'BigDataSecurity',
    'Bioinform.',
    'Biomed. Signal Process. Control.',
    'BlockSys',
    'CCCI',
    'CCF Trans. Netw.',
    'CCF Trans. Pervasive Comput. Interact.',
    'CCNC',
    'CHI',
    'CICAI',
    'CIKM',
    'CIKM Workshops',
    'CISP-BMEI',
    'CIoT',
    'CLOUD',
    'CRC',
    'CSAE',
    'CSCWD',
    'CVPR',
    'CVPR Workshops',
    'ChinaCom',
    'Circuits Syst. Signal Process.',
    'CoRR',
    'CollaborateCom (1)',
    'CollaborateCom (2)',
    'Color Imaging: Displaying, Processing, Hardcopy, and Applications',
    'Complex.',
    'Comput. Aided Civ. Infrastructure Eng.',
    'Comput. Appl. Math.',
    'Comput. Biol. Medicine',
    'Comput. Commun.',
    'Comput. Electr. Eng.',
    'Comput. Graph. Forum',
    'Comput. Ind. Eng.',
    'Comput. Math. Appl.',
    'Comput. Methods Programs Biomed.',
    'Comput. Networks',
    'Comput. Sci. Inf. Syst.',
    'Comput. Secur.',
    'Comput. Syst. Sci. Eng.',
    'Comput. Vis. Image Underst.',
    'Computing',
    'Concurr. Comput. Pract. Exp.',
    'DAC',
    'DAS',
    'DASC/PiCom/CBDCom/CyberSciTech',
    'DCC',
    'DIVANet',
    'Digit. Commun. Networks',
    'Digit. Signal Process.',
    'Displays',
    'ECCV (1)',
    'ECCV (11)',
    'ECCV (12)',
    'ECCV (17)',
    'ECCV (2)',
    'ECCV (20)',
    'ECCV (21)',
    'ECCV (22)',
    'ECCV (23)',
    'ECCV (24)',
    'ECCV (25)',
    'ECCV (29)',
    'ECCV (4)',
    'ECCV (5)',
    'ECCV (6)',
    'ECCV (7)',
    'ECCV (8)',
    'ECCV (9)',
    'ECCV Workshops (3)',
    'ECCV Workshops (4)',
    'ECCV Workshops (5)',
    'EDGE',
    'EIDWT',
    'ERVR',
    'EUC',
    'EURASIP J. Adv. Signal Process.',
    'EURASIP J. Image Video Process.',
    'EURASIP J. Wirel. Commun. Netw.',
    'EUSIPCO',
    'Entropy',
    'EuroSys',
    'Expert Syst. Appl.',
    'Expert Syst. J. Knowl. Eng.',
    'Frontiers Appl. Math. Stat.',
    'Frontiers Inf. Technol. Electron. Eng.',
    'Future Gener. Comput. Syst.',
    'GCCE',
    'GLOBECOM',
    'GLOBECOM (Workshops)',
    'Genom. Proteom. Bioinform.',
    'Graph. Model.',
    'HCI (23)',
    'HPCC/DSS/SmartCity',
    'HPCC/DSS/SmartCity/DependSys',
    'I2MTC',
    'IC-NIDC',
    'IC2E',
    'ICA3PP (1)',
    'ICA3PP (2)',
    'ICACI',
    'ICAIIC',
    'ICAIS (1)',
    'ICAIS (2)',
    'ICAIS (3)',
    'ICANN (3)',
    'ICANN (5)',
    'ICASSP',
    'ICC',
    'ICC Workshops',
    'ICCAD',
    'ICCC',
    'ICCCN',
    'ICCCS',
    'ICCDE',
    'ICCE',
    'ICCP',
    'ICCT',
    'ICCV',
    'ICCVW',
    'ICDCS',
    'ICIG (3)',
    'ICIP',
    'ICLR',
    'ICME',
    'ICME Workshops',
    'ICML',
    'ICMLC',
    'ICMR',
    'ICN',
    'ICNC',
    'ICNP',
    'ICNSC',
    'ICOIN',
    'ICONIP (6)',
    'ICPADS',
    'ICPR',
    'ICSOC',
    'ICT-DM',
    'ICTAI',
    'ICWS',
    'IECON',
    'IEEE ACM Trans. Audio Speech Lang. Process.',
    'IEEE Access',
    'IEEE CAA J. Autom. Sinica',
    'IEEE Commun. Lett.',
    'IEEE Commun. Mag.',
    'IEEE Commun. Stand. Mag.',
    'IEEE Commun. Surv. Tutorials',
    'IEEE Geosci. Remote. Sens. Lett.',
    'IEEE Internet Things J.',
    'IEEE Internet Things Mag.',
    'IEEE J. Biomed. Health Informatics',
    'IEEE J. Sel. Areas Commun.',
    'IEEE J. Sel. Top. Appl. Earth Obs. Remote. Sens.',
    'IEEE J. Sel. Top. Signal Process.',
    'IEEE Multim.',
    'IEEE Netw.',
    'IEEE Netw. Lett.',
    'IEEE Open J. Commun. Soc.',
    'IEEE Open J. Comput. Soc.',
    'IEEE Signal Process. Lett.',
    'IEEE Syst. J.',
    'IEEE Trans. Big Data',
    'IEEE Trans. Biomed. Eng.',
    'IEEE Trans. Broadcast.',
    'IEEE Trans. Circuits Syst. I Regul. Pap.',
    'IEEE Trans. Circuits Syst. II Express Briefs',
    'IEEE Trans. Circuits Syst. Video Technol.',
    'IEEE Trans. Cloud Comput.',
    'IEEE Trans. Cogn. Commun. Netw.',
    'IEEE Trans. Commun.',
    'IEEE Trans. Comput. Aided Des. Integr. Circuits Syst.',
    'IEEE Trans. Comput. Soc. Syst.',
    'IEEE Trans. Computational Imaging',
    'IEEE Trans. Computers',
    'IEEE Trans. Consumer Electron.',
    'IEEE Trans. Cybern.',
    'IEEE Trans. Dependable Secur. Comput.',
    'IEEE Trans. Emerg. Top. Comput.',
    'IEEE Trans. Emerg. Top. Comput. Intell.',
    'IEEE Trans. Geosci. Remote. Sens.',
    'IEEE Trans. Green Commun. Netw.',
    'IEEE Trans. Image Process.',
    'IEEE Trans. Ind. Informatics',
    'IEEE Trans. Inf. Forensics Secur.',
    'IEEE Trans. Instrum. Meas.',
    'IEEE Trans. Intell. Transp. Syst.',
    'IEEE Trans. Medical Imaging',
    'IEEE Trans. Mob. Comput.',
    'IEEE Trans. Multim.',
    'IEEE Trans. Netw. Sci. Eng.',
    'IEEE Trans. Netw. Serv. Manag.',
    'IEEE Trans. Neural Networks Learn. Syst.',
    'IEEE Trans. Parallel Distributed Syst.',
    'IEEE Trans. Pattern Anal. Mach. Intell.',
    'IEEE Trans. Serv. Comput.',
    'IEEE Trans. Signal Process.',
    'IEEE Trans. Smart Grid',
    'IEEE Trans. Sustain. Comput.',
    'IEEE Trans. Syst. Man Cybern. Syst.',
    'IEEE Trans. Veh. Technol.',
    'IEEE Trans. Vis. Comput. Graph.',
    'IEEE Trans. Wirel. Commun.',
    'IEEE Veh. Technol. Mag.',
    'IEEE Wirel. Commun.',
    'IEEE Wirel. Commun. Lett.',
    'IEEE/ACM Trans. Netw.',
    'IEICE Trans. Fundam. Electron. Commun. Comput. Sci.',
    'IEICE Trans. Inf. Syst.',
    'IET Circuits Devices Syst.',
    'IET Commun.',
    'IET Image Process.',
    'IGARSS',
    'IJCAI',
    'IJCNN',
    'INFOCOM',
    'INFOCOM Workshops',
    'IPCCC',
    'IPDPS',
    'ISBI',
    'ISBI Workshops',
    'ISCAS',
    'ISCC',
    'ISM',
    'ISMAR',
    'ISPA/BDCloud/SocialCom/SustainCom',
    'ITSC',
    'IV',
    'IWCMC',
    'IWQoS',
    'Inf.',
    'Inf. Fusion',
    'Inf. Sci.',
    'Int. J. Appl. Earth Obs. Geoinformation',
    'Int. J. Artif. Intell. Tools',
    'Int. J. Commun. Syst.',
    'Int. J. Comput. Assist. Radiol. Surg.',
    'Int. J. Comput. Vis.',
    'Int. J. Data Sci. Anal.',
    'Int. J. Digit. Earth',
    'Int. J. Geogr. Inf. Sci.',
    'Int. J. Mach. Learn. Cybern.',
    'Int. J. Parallel Program.',
    'Int. J. Pattern Recognit. Artif. Intell.',
    'Int. J. Syst. Assur. Eng. Manag.',
    'Int. J. Web Grid Serv.',
    'Int. J. Web Serv. Res.',
    'Int. J. Wirel. Mob. Comput.',
    'Int. Trans. Oper. Res.',
    'J. Adv. Comput. Intell. Intell. Informatics',
    'J. Ambient Intell. Humaniz. Comput.',
    'J. Chem. Inf. Model.',
    'J. Circuits Syst. Comput.',
    'J. Cloud Comput.',
    'J. Comput. Appl. Math.',
    'J. Comput. Sci. Technol.',
    'J. Electronic Imaging',
    'J. Frankl. Inst.',
    'J. Intell. Fuzzy Syst.',
    'J. Netw. Comput. Appl.',
    'J. Real Time Image Process.',
    'J. Reliab. Intell. Environ.',
    'J. Sensors',
    'J. Supercomput.',
    'J. Syst. Archit.',
    'J. Vis. Commun. Image Represent.',
    'Kaleidoscope',
    'Knowl. Based Syst.',
    'LCN',
    'MASS',
    'MICCAI (1)',
    'MICCAI (6)',
    'MICCAI (7)',
    'MIPR',
    'ML4CS (1)',
    'MLMI@MICCAI',
    'MLMIR@MICCAI',
    'MMAsia',
    'MMM (1)',
    'MMM (2)',
    'MMSP',
    'MMSys',
    'MONAMI',
    'MSN',
    'MSWiM',
    'MVA',
    'Mach. Vis. Appl.',
    'MeMeA',
    'Medical Image Anal.',
    'MeditCom',
    'Mob. Inf. Syst.',
    'Mob. Networks Appl.',
    'MobiCom',
    'Multim. Tools Appl.',
    'NOMS',
    'NOSSDAV',
    'NPC',
    'NSDI',
    'NaNA',
    'NeurIPS',
    'Neural Comput. Appl.',
    'Neural Networks',
    'Neural Process. Lett.',
    'NeuroImage',
    'Neurocomputing',
    'OFC',
    'ONDM',
    'PAAP',
    'PCS',
    'PIMRC',
    'PRCV (1)',
    'PRCV (3)',
    'Pattern Recognit.',
    'Pattern Recognit. Lett.',
    'Peer-to-Peer Netw. Appl.',
    'PeerJ Comput. Sci.',
    'PerCom Workshops',
    'Pervasive Mob. Comput.',
    'Proc. ACM Interact. Mob. Wearable Ubiquitous Technol.',
    'ROBIO',
    'Reliab. Eng. Syst. Saf.',
    'Remote. Sens.',
    'Robotics Comput. Integr. Manuf.',
    'SCC',
    'SEC',
    'SECON',
    'SERVICES',
    'SIAM J. Imaging Sci.',
    'SIGCOMM',
    'SIGCOMM Posters and Demos',
    'SIGGRAPH ASIA Posters',
    'SIGGRAPH Asia Technical Communications',
    'SMC',
    'Sci. China Inf. Sci.',
    'Sci. Program.',
    'Secur. Commun. Networks',
    'Sensors',
    'Signal Image Video Process.',
    'Signal Process.',
    'Signal Process. Image Commun.',
    'Simul. Model. Pract. Theory',
    'SmartCloud',
    'Soft Comput.',
    'Softw. Pract. Exp.',
    'Symmetry',
    'Trans. Emerg. Telecommun. Technol.',
    'TrustCom',
    'Turkish J. Electr. Eng. Comput. Sci.',
    'UCC',
    'UCET',
    'UIST',
    'USENIX Annual Technical Conference',
    'VCIP',
    'VR',
    'VR Workshops',
    'VTC Fall',
    'VTC Spring',
    'Vis. Comput.',
    'WACV',
    'WACV (Workshops)',
    'WASA (1)',
    'WCNC',
    'WCSP',
    'WOWMOM',
    'WWW',
    'WiMob',
    'Wirel. Commun. Mob. Comput.',
    'Wirel. Networks',
    'Wirel. Pers. Commun.'
}
